/*
 *
 * MassagePage constants
 *
 */

const prefix = 'massage/'

export const LOAD_MASSAGE_INFO_REQUEST = `${prefix}LOAD_MASSAGE_INFO_REQUEST`;
export const LOAD_MASSAGE_INFO_SUCCESS = `${prefix}LOAD_MASSAGE_INFO_SUCCESS`;
export const LOAD_MASSAGE_INFO_FAIL = `${prefix}LOAD_MASSAGE_INFO_FAIL`;

export const LOAD_MASSAGE_OPTIONS_REQUEST = `${prefix}LOAD_MASSAGE_OPTIONS_REQUEST`;
export const LOAD_MASSAGE_OPTIONS_SUCCESS = `${prefix}LOAD_MASSAGE_OPTIONS_SUCCESS`;
export const LOAD_MASSAGE_OPTIONS_FAIL = `${prefix}LOAD_MASSAGE_OPTIONS_FAIL`;

export const LOAD_MASSAGE_INGREDIENTS_REQUEST = `${prefix}LOAD_MASSAGE_INGREDIENTS_REQUEST`; 
export const LOAD_MASSAGE_INGREDIENTS_SUCCESS = `${prefix}LOAD_MASSAGE_INGREDIENTS_SUCCESS`;
export const LOAD_MASSAGE_INGREDIENTS_FAIL = `${prefix}LOAD_MASSAGE_INGREDIENTS_FAIL`;

export const LOAD_MASSAGE_SLIDES_REQUEST = `${prefix}LOAD_MASSAGE_SLIDES_REQUEST`; 
export const LOAD_MASSAGE_SLIDES_SUCCESS = `${prefix}LOAD_MASSAGE_SLIDES_SUCCESS`;
export const LOAD_MASSAGE_SLIDES_FAIL = `${prefix}LOAD_MASSAGE_SLIDES_FAIL`;

export const LOAD_MASSAGE_QA_REQUEST = `${prefix}LOAD_MASSAGE_QA_REQUEST`; 
export const LOAD_MASSAGE_QA_SUCCESS = `${prefix}LOAD_MASSAGE_QA_SUCCESS`;
export const LOAD_MASSAGE_QA_FAIL = `${prefix}LOAD_MASSAGE_QA_FAIL`;