/*
 *
 * MassagePage constants
 *
 */

const prefix = 'im_shots/'

export const LOAD_BOOSTER_SHOT_INFO_REQUEST = `${prefix}LOAD_BOOSTER_SHOT_INFO_REQUEST`;
export const LOAD_BOOSTER_SHOT_INFO_SUCCESS = `${prefix}LOAD_BOOSTER_SHOT_INFO_SUCCESS`;
export const LOAD_BOOSTER_SHOT_INFO_FAIL = `${prefix}LOAD_BOOSTER_SHOT_INFO_FAIL`;

export const LOAD_BOOSTER_SHOT_OPTIONS_REQUEST = `${prefix}LOAD_BOOSTER_SHOT_OPTIONS_REQUEST`;
export const LOAD_BOOSTER_SHOT_OPTIONS_SUCCESS = `${prefix}LOAD_BOOSTER_SHOT_OPTIONS_SUCCESS`;
export const LOAD_BOOSTER_SHOT_OPTIONS_FAIL = `${prefix}LOAD_BOOSTER_SHOT_OPTIONS_FAIL`;

export const LOAD_BOOSTER_SHOT_INGREDIENTS_REQUEST = `${prefix}LOAD_BOOSTER_SHOT_INGREDIENTS_REQUEST`; 
export const LOAD_BOOSTER_SHOT_INGREDIENTS_SUCCESS = `${prefix}LOAD_BOOSTER_SHOT_INGREDIENTS_SUCCESS`;
export const LOAD_BOOSTER_SHOT_INGREDIENTS_FAIL = `${prefix}LOAD_BOOSTER_SHOT_INGREDIENTS_FAIL`;

export const LOAD_BOOSTER_SHOT_QA_REQUEST = `${prefix}LOAD_BOOSTER_SHOT_QA_REQUEST`; 
export const LOAD_BOOSTER_SHOT_QA_SUCCESS = `${prefix}LOAD_BOOSTER_SHOT_QA_SUCCESS`;
export const LOAD_BOOSTER_SHOT_QA_FAIL = `${prefix}LOAD_BOOSTER_SHOT_QA_FAIL`;
