/*
 *
 * CryoPage constants
 *
 */

const prefix = 'cryo_therapy/'

export const LOAD_CRYO_THERAPY_INFO_REQUEST = `${prefix}LOAD_CRYO_THERAPY_INFO_REQUEST`;
export const LOAD_CRYO_THERAPY_INFO_SUCCESS = `${prefix}LOAD_CRYO_THERAPY_INFO_SUCCESS`;
export const LOAD_CRYO_THERAPY_INFO_FAIL = `${prefix}LOAD_CRYO_THERAPY_INFO_FAIL`;

export const LOAD_CRYO_THERAPY_OPTIONS_REQUEST = `${prefix}LOAD_CRYO_THERAPY_OPTIONS_REQUEST`;
export const LOAD_CRYO_THERAPY_OPTIONS_SUCCESS = `${prefix}LOAD_CRYO_THERAPY_OPTIONS_SUCCESS`;
export const LOAD_CRYO_THERAPY_OPTIONS_FAIL = `${prefix}LOAD_CRYO_THERAPY_OPTIONS_FAIL`;

export const LOAD_CRYO_THERAPY_SLIDES_REQUEST = `${prefix}LOAD_CRYO_THERAPY_SLIDES_REQUEST`;
export const LOAD_CRYO_THERAPY_SLIDES_SUCCESS = `${prefix}LOAD_CRYO_THERAPY_SLIDES_SUCCESS`;
export const LOAD_CRYO_THERAPY_SLIDES_FAIL = `${prefix}LOAD_CRYO_THERAPY_SLIDES_FAIL`;

export const LOAD_CRYO_THERAPY_QA_REQUEST = `${prefix}LOAD_CRYO_THERAPY_QA_REQUEST`;
export const LOAD_CRYO_THERAPY_QA_SUCCESS = `${prefix}LOAD_CRYO_THERAPY_QA_SUCCESS`;
export const LOAD_CRYO_THERAPY_QA_FAIL = `${prefix}LOAD_CRYO_THERAPY_QA_FAIL`;


