const prefix = 'account/'

export const CREATE_NEW_USER_REQUEST = `${prefix}CREATE_NEW_USER__REQUEST`;
export const CREATE_NEW_USER_SUCCESS = `${prefix}CREATE_NEW_USER__SUCCESS`;
export const CREATE_NEW_USER_FAIL = `${prefix}CREATE_NEW_USER_FAIL`;

export const LOAD_USER_INFO_REQUEST = `${prefix}LOAD_USER_INFO_REQUEST`;
export const LOAD_USER_INFO_SUCCESS = `${prefix}LOAD_USER_INFO_SUCCESS`;
export const LOAD_USER_INFO_FAIL = `${prefix}LOAD_USER_INFO_FAIL`;

export const UPDATE_USER_INFO_REQUEST = `${prefix}UPDATE_USER_INFO_REQUEST`;
export const UPDATE_USER_INFO_SUCCESS = `${prefix}UPDATE_USER_INFO_SUCCESS`;
export const UPDATE_USER_INFO_FAIL = `${prefix}UPDATE_USER_INFO_FAIL`;

export const ADD_NEW_CREDIT_CARD_REQUEST = `${prefix}ADD_NEW_CREDIT_CARD_REQUEST`;
export const ADD_NEW_CREDIT_CARD_SUCCESS = `${prefix}ADD_NEW_CREDIT_CARD_SUCCESS`;
export const ADD_NEW_CREDIT_CARD_FAIL = `${prefix}ADD_NEW_CREDIT_CARD_FAIL`;

export const DELETE_CREDIT_CARD_REQUEST = `${prefix}DELETE_CREDIT_CARD_REQUEST`;
export const DELETE_CREDIT_CARD_SUCCESS = `${prefix}DELETE_CREDIT_CARD_SUCCESS`;
export const DELETE_CREDIT_CARD_FAIL = `${prefix}DELETE_CREDIT_CARD_FAIL`;

export const LOAD_CREDIT_CARDS_REQUEST = `${prefix}LOAD_CREDIT_CARDS_REQUEST`;
export const LOAD_CREDIT_CARDS_SUCCESS = `${prefix}LOAD_CREDIT_CARDS_SUCCESS`;
export const LOAD_CREDIT_CARDS_FAIL = `${prefix}LOAD_CREDIT_CARDS_FAIL`;

export const LOAD_APPOINTMENTS_REQUEST = `${prefix}LOAD_APPOINTMENTS_REQUEST`;
export const LOAD_APPOINTMENTS_SUCCESS = `${prefix}LOAD_APPOINTMENTS_SUCCESS`;
export const LOAD_APPOINTMENTS_FAIL = `${prefix}LOAD_APPOINTMENTS_FAIL`;
