/*
 *
 * IvDripPage constants
 *
 */

const prefix = 'iv_drip/'

export const LOAD_IV_DRIPS_INFO_REQUEST = `${prefix}LOAD_IV_DRIPS_INFO_REQUEST`;
export const LOAD_IV_DRIPS_INFO_SUCCESS = `${prefix}LOAD_IV_DRIPS_INFO_SUCCESS`;
export const LOAD_IV_DRIPS_INFO_FAIL = `${prefix}LOAD_IV_DRIPS_INFO_FAIL`;

export const LOAD_IV_DRIPS_OPTIONS_REQUEST = `${prefix}LOAD_IV_DRIPS_OPTIONS_REQUEST`;
export const LOAD_IV_DRIPS_OPTIONS_SUCCESS = `${prefix}LOAD_IV_DRIPS_OPTIONS_SUCCESS`;
export const LOAD_IV_DRIPS_OPTIONS_FAIL = `${prefix}LOAD_IV_DRIPS_OPTIONS_FAIL`;

export const LOAD_IV_DRIPS_INGREDIENTS_REQUEST = `${prefix}LOAD_IV_DRIPS_INGREDIENTS_REQUEST`; 
export const LOAD_IV_DRIPS_INGREDIENTS_SUCCESS = `${prefix}LOAD_IV_DRIPS_INGREDIENTS_SUCCESS`;
export const LOAD_IV_DRIPS_INGREDIENTS_FAIL = `${prefix}LOAD_IV_DRIPS_INGREDIENTS_FAIL`;

export const LOAD_IV_DRIPS_QA_REQUEST = `${prefix}LOAD_IV_DRIPS_QA_REQUEST`; 
export const LOAD_IV_DRIPS_QA_SUCCESS = `${prefix}LOAD_IV_DRIPS_QA_SUCCESS`;
export const LOAD_IV_DRIPS_QA_FAIL = `${prefix}LOAD_IV_DRIPS_QA_FAIL`;